name: make-books 
run-name: ${{ github.actor }} is making books
on:
  push:
    branches:
      - main
jobs:
  make-books:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make ebooks
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/books.sh
