name: validate-content 
run-name: ${{ github.actor }} is validating content
on: [push, pull_request]
jobs:
  lint-snippets:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: echo $PATH
        shell: bash
      - run: bash ${GITHUB_WORKSPACE}/.github/workflows/lint.sh
  compile-snippets:
    runs-on: ubuntu-latest
    steps:
      - run: bash ${GITHUB_WORKSPACE}/.github/workflows/compile.sh

      