name: validate-content 
run-name: ${{ github.actor }} is validating content
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint script
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/lint.sh
  compile-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run compile script
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/compile.sh
      - name: GIT Commit Build Artifacts ebooks 
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/books.sh

      